### ISSUE TITLE
Minor: can clip and see past the walls and ceiling

### ISSUE THREAD

**Issue by annehe9** [gcwhitfield/15-466-final-game#15]
As the cat, I can clip through the walls and fly so that the camera passes through the ceiling or is right next to the wall outside. This is particularly reproducible in the upper right corner, where there is a random rectangular prism segment outside, but I can clip through all the walls using this same method. If I transform between cat and human while moving into the wall I can clip further into the wall.

**Comment by ArthasZhang007** [comment]
Any suggestions of how to fix on this?

**Comment by annehe9** [comment]
Perhaps you can increase the width of the cat collider? This should also fix the camera issue since I find I can only look outside the scene if the player has clipped through the wall. The collider for the capsule shaped player is fine and works if the player is not currently in the wall, you just need to prevent the cat from going through the wall.

**Comment by bcagan** [comment]
The camera uses the walkmesh, its unrelated to the collider. We are considering redoing the walkmesh to fix the camera issue, hopefully (itll be a bit tricky since it has to be redone from scratch though :/ )
