### ISSUE TITLE
Minor: camera gets stuck, can't see player

### ISSUE THREAD

**Issue by sidsahay** [gcwhitfield/15-466-final-game#16]
Platform: MacOS Big Sur, M1 Mac Air
Steps: Cat mode -> go high in air -> Human mode -> Cat mode -> camera stuck in view above player for quite a while
It's inconsistent, I've only gotten this to work once. Might just be a fluke.

**Comment by bcagan** [comment]
Can you give more specifics on where this happened, and what you were doing when it was?
