### ISSUE TITLE
Build does not start on Linux

### ISSUE THREAD

**Issue by ixchow** [gcwhitfield/15-466-final-game#17]
```
game6-linux-v1.0.1$ ./game 
Error creating OpenGL context: Could not make GL context current: BadMatch (invalid parameter attributes)
```
The issue here is that the window is created before the gl attributes were set -- consider initializing `window` to null at the global scope then setting `window = SDL_CreateWindow(...)` during the normal flow of code in main.

**Comment by lisigg1998** [comment]
The build works on Github Actions and the generated linux build can run on ubuntu 20.04 LTS. Need more time to figure it out.

**Comment by ixchow** [comment]
please note that literally doing what I say in the comment above solves the problem for me; even on other OS's, this is incorrect use of SDL (calling CreateWindow before initializing the library).

**Comment by lisigg1998** [comment]
Solved. The latest commit can build on Ubuntu 20.04 LTS now.
